basePath: /backend/api/v1
definitions:
  util.SDK:
    properties:
      noncestr:
        type: string
      signature:
        type: string
      timestamp:
        type: integer
    type: object
  v1.InviteVisitorsRecordListDate:
    properties:
      count:
        type: integer
      items:
        items:
          $ref: '#/definitions/v1.InviteVisitorsRecordListItem'
        type: array
    type: object
  v1.InviteVisitorsRecordListItem:
    properties:
      accompany_num:
        type: integer
      address:
        type: string
      city:
        type: string
      date:
        type: string
      district:
        type: string
      id:
        type: integer
      invitation_reason:
        type: string
      invitee_cellphone:
        type: string
      invitee_company_name:
        type: string
      invitee_duty:
        type: string
      invitee_real_name:
        type: string
      inviter_cellphone:
        type: string
      inviter_real_name:
        type: string
      location_lat:
        type: number
      location_lon:
        type: number
      province:
        type: string
      status:
        type: string
      template_name:
        type: string
      time:
        type: string
      type:
        type: string
    type: object
  v1.Result:
    properties:
      code:
        description: return code, 0 for succ
        type: integer
      data:
        description: data object
        type: object
      msg:
        description: message
        type: string
    type: object
  v1.UserAccountCheckData:
    properties:
      exist:
        type: boolean
    type: object
  v1.UserLoginData:
    properties:
      token:
        type: string
    type: object
  v1.UserLoginParam:
    properties:
      code:
        type: string
      login_type:
        type: string
      password:
        type: string
      phone_number:
        type: string
      username:
        type: string
    type: object
host: etong.vsattech.com
info:
  contact: {}
  description: 接口文档
  license: {}
  title: 易通后端API文档
  version: "1.0"
paths:
  /address:
    delete:
      consumes:
      - application/json
      description: 删除用户地址
      parameters:
      - description: 地址id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.Result'
      summary: 删除用户地址
      tags:
      - 地址管理
    post:
      consumes:
      - application/json
      description: 增加用户地址
      parameters:
      - description: 省
        in: query
        name: province
        required: true
        type: string
      - description: 城市
        in: query
        name: city
        required: true
        type: integer
      - description: 区/县
        in: query
        name: district
        required: true
        type: string
      - description: 详细地址
        in: query
        name: addr
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.Result'
      summary: 增加用户地址
      tags:
      - 地址管理
    put:
      consumes:
      - application/json
      description: 更新用户地址
      parameters:
      - description: 地址id
        in: query
        name: id
        required: true
        type: integer
      - description: 省
        in: query
        name: province
        type: string
      - description: 城市
        in: query
        name: city
        type: integer
      - description: 区/县
        in: query
        name: district
        type: string
      - description: 详细地址
        in: query
        name: addr
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.Result'
      summary: 更新用户地址
      tags:
      - 地址管理
  /address/item:
    get:
      consumes:
      - application/json
      description: 获取用户地址信息
      parameters:
      - description: 地址id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.Result'
      summary: 获取用户地址信息
      tags:
      - 地址管理
  /address/list:
    get:
      consumes:
      - application/json
      description: 获取用户地址列表
      parameters:
      - description: page(默认1)
        in: query
        name: page
        type: integer
      - description: limit(默认10)
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.Result'
      summary: 获取用户地址列表
      tags:
      - 地址管理
  /user/account/check:
    get:
      consumes:
      - application/json
      description: 检查账号是否存在
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.UserAccountCheckData'
      summary: 账号检测
      tags:
      - 用户
  /user/login:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: login params
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/v1.UserLoginParam'
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.UserLoginData'
      summary: 登录
      tags:
      - 用户
  /visitor/invite:
    post:
      consumes:
      - application/json
      description: 邀请访客
      parameters:
      - description: 被邀请人手机号
        in: query
        name: invitee_cellphone
        required: true
        type: string
      - description: 邀请日期
        in: query
        name: date
        required: true
        type: integer
      - description: 邀请时间
        in: query
        name: time
        type: string
      - description: 被邀请人真实姓名
        in: query
        name: invitee_real_name
        required: true
        type: string
      - description: 被邀请人公司
        in: query
        name: invitee_company_name
        type: string
      - description: 邀请理由
        in: query
        name: invitation_reason
        type: string
      - description: 被邀请人职务
        in: query
        name: invitee_duty
        type: string
      - description: 随行人数
        in: query
        name: accompany_num
        type: integer
      - description: 邀请模板
        in: query
        name: template_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.UserLoginData'
      summary: 邀请访客
      tags:
      - 邀请函
  /visitor/invite/item:
    get:
      consumes:
      - application/json
      description: 获取单个邀请记录
      parameters:
      - description: 邀请id
        in: query
        name: invite_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.InviteVisitorsRecordListItem'
      summary: 获取单个邀请记录
      tags:
      - 邀请函
  /visitor/invite/list:
    get:
      consumes:
      - application/json
      description: 邀请访客列表
      parameters:
      - description: 被邀请人手机号
        in: query
        name: invitee_cellphone
        type: string
      - description: 邀请人手机号
        in: query
        name: inviter_cellphone
        type: string
      - description: inviter or invitee
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.InviteVisitorsRecordListDate'
      summary: 邀请访客列表
      tags:
      - 邀请函
  /visitor/personal/invite:
    post:
      consumes:
      - application/json
      description: 邀请访客
      parameters:
      - description: 被邀请人手机号
        in: query
        name: invitee_cellphone
        required: true
        type: string
      - description: 邀请日期
        in: query
        name: date
        required: true
        type: integer
      - description: 邀请时间
        in: query
        name: time
        type: string
      - description: 被邀请人真实姓名
        in: query
        name: invitee_real_name
        required: true
        type: string
      - description: 被邀请人公司
        in: query
        name: invitee_company_name
        type: string
      - description: 邀请理由
        in: query
        name: invitation_reason
        type: string
      - description: 被邀请人职务
        in: query
        name: invitee_duty
        type: string
      - description: 随行人数
        in: query
        name: accompany_num
        type: integer
      - description: 邀请模板
        in: query
        name: template_name
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/v1.UserLoginData'
      summary: 邀请访客
      tags:
      - 邀请函
  /wechart/sdk/config:
    get:
      consumes:
      - application/json
      description: 获取微信sdk-config
      parameters:
      - description: url
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: desc
          schema:
            $ref: '#/definitions/util.SDK'
      summary: 获取微信sdk-config
      tags:
      - WeChart
schemes:
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
  BasicAuth:
    type: basic
  OAuth2AccessCode:
    authorizationUrl: https://example.com/oauth/authorize
    flow: accessCode
    scopes:
      admin: ' Grants read and write access to administrative information'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
  OAuth2Application:
    flow: application
    scopes:
      admin: ' Grants read and write access to administrative information'
      write: ' Grants write access'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
  OAuth2Implicit:
    authorizationUrl: https://example.com/oauth/authorize
    flow: implicit
    scopes:
      admin: ' Grants read and write access to administrative information'
      write: ' Grants write access'
    type: oauth2
  OAuth2Password:
    flow: password
    scopes:
      admin: ' Grants read and write access to administrative information'
      read: ' Grants read access'
      write: ' Grants write access'
    tokenUrl: https://example.com/oauth/token
    type: oauth2
swagger: "2.0"
x-extension-openapi:
  example: value on a json format
